
name: Versioned Docs Sync

on:
  push:
    branches:
      - 'release-1.1.0'

jobs:
  sync-versioned-content:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: Sync versioned content
        env:
          HC_AWS_ACCESS_KEY_ID: ${{ secrets.HC_AWS_ACCESS_KEY_ID }}
          HC_AWS_SECRET_ACCESS_KEY: ${{ secrets.HC_AWS_SECRET_ACCESS_KEY }}
        run: npx -p @hashicorp/versioned-docs versioned-docs-sync $GITHUB_REF $GITHUB_SHA ${{ github.event.repository.name }}
